import { describe, expect, it } from 'vitest';
import {
  COOKBOOK_CHAPTERS,
  COOKBOOK_ID,
  COOKBOOK_TITLE,
  FRONT_MATTER,
  BACK_MATTER,
  TARGET_RECIPE_COUNT,
  RECIPES_PER_CHAPTER,
  getChapterById,
  getChapterByOrder,
  getChapterIds,
  getTotalTargetRecipeCount,
} from './structure';
import {
  CLASSIFICATION_DEFINITIONS,
  getClassificationDefinition,
  getClassificationByLabel,
  getClassificationLabels,
  CLASSIFICATION_RULES,
} from './classification-guide';
import {
  EVIDENCE_RULES,
  EVIDENCE_PROHIBITIONS,
  HISTORICAL_CLAIM_RULES,
  SCRIPTURE_RULES,
  UNCERTAINTY_RULES,
  RECONSTRUCTION_RULES,
} from './evidence-rules';
import {
  RECIPE_SECTIONS,
  RECIPE_PRESENTATION_METADATA,
  getRequiredFieldsForClassification,
} from './recipe-template';

describe('V3C.44A cookbook structure', () => {
  it('defines exactly one canonical cookbook ID', () => {
    expect(COOKBOOK_ID).toBe('biblicalmeal-cookbook-v1');
    expect(typeof COOKBOOK_ID).toBe('string');
  });

  it('defines a canonical cookbook title', () => {
    expect(COOKBOOK_TITLE).toBe(
      'Biblical Meals: Recipes Inspired by the Foods of the Bible',
    );
  });

  it('defines six chapters', () => {
    expect(COOKBOOK_CHAPTERS).toHaveLength(6);
  });

  it('has correct chapter ordering', () => {
    const orders = COOKBOOK_CHAPTERS.map((chapter) => chapter.order);
    expect(orders).toEqual([1, 2, 3, 4, 5, 6]);
  });

  it('has unique chapter IDs', () => {
    const ids = COOKBOOK_CHAPTERS.map((chapter) => chapter.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('has target recipe count of 30', () => {
    expect(TARGET_RECIPE_COUNT).toBe(30);
  });

  it('has 5 recipes per chapter target', () => {
    expect(RECIPES_PER_CHAPTER).toBe(5);
  });

  it('total target recipe count matches expected', () => {
    expect(getTotalTargetRecipeCount()).toBe(30);
  });

  it('can retrieve chapter by ID', () => {
    const chapter = getChapterById('grains-breads');
    expect(chapter).toBeDefined();
    expect(chapter?.title).toBe('Grains & Breads');
  });

  it('can retrieve chapter by order', () => {
    const chapter = getChapterByOrder(1);
    expect(chapter).toBeDefined();
    expect(chapter?.id).toBe('grains-breads');
  });

  it('can get all chapter IDs in order', () => {
    const ids = getChapterIds();
    expect(ids).toEqual([
      'grains-breads',
      'legumes-one-pot-meals',
      'fruits-preserves',
      'fish-seafood',
      'herbs-oils-seasonings',
      'feasts-gatherings',
    ]);
  });

  it('defines front matter components', () => {
    expect(FRONT_MATTER.length).toBeGreaterThan(0);
  });

  it('has correct front matter ordering', () => {
    const orders = FRONT_MATTER.map((component) => component.order);
    const sorted = [...orders].sort((a, b) => a - b);
    expect(orders).toEqual(sorted);
  });

  it('defines back matter components', () => {
    expect(BACK_MATTER.length).toBeGreaterThan(0);
  });

  it('has correct back matter ordering', () => {
    const orders = BACK_MATTER.map((component) => component.order);
    const sorted = [...orders].sort((a, b) => a - b);
    expect(orders).toEqual(sorted);
  });

  it('has methodology front matter referencing existing content', () => {
    const methodology = FRONT_MATTER.find((c) => c.id === 'methodology');
    expect(methodology).toBeDefined();
    expect(methodology?.existingContentSource).toBe(
      'src/content/articles/how-we-research.mdx',
    );
  });

  it('has auto-generated back matter components', () => {
    const autoGenerated = BACK_MATTER.filter((c) => c.autoGenerated);
    expect(autoGenerated.length).toBeGreaterThan(0);
  });
});

describe('V3C.44A recipe classification guide', () => {
  it('defines four classification definitions', () => {
    expect(CLASSIFICATION_DEFINITIONS).toHaveLength(4);
  });

  it('has unique classification labels', () => {
    const labels = CLASSIFICATION_DEFINITIONS.map((d) => d.label);
    expect(new Set(labels).size).toBe(labels.length);
  });

  it('can retrieve classification by type', () => {
    const def = getClassificationDefinition('scripture-inspired-preparation');
    expect(def).toBeDefined();
    expect(def?.label).toBe('Inspired');
  });

  it('can retrieve classification by label', () => {
    const def = getClassificationByLabel('Researched');
    expect(def).toBeDefined();
    expect(def?.classification).toBe('historically-attested-preparation');
  });

  it('can get all classification labels', () => {
    const labels = getClassificationLabels();
    expect(labels).toEqual([
      'Inspired',
      'Researched',
      'Reconstructed',
      'Historically-Informed',
    ]);
  });

  it('defines classification rules', () => {
    expect(CLASSIFICATION_RULES.mustBeExplicit).toBe(true);
    expect(CLASSIFICATION_RULES.cannotUpgradeWithoutEvidence).toBe(true);
    expect(CLASSIFICATION_RULES.uncertaintyMustBeVisible).toBe(true);
    expect(CLASSIFICATION_RULES.modernAdaptationsMustBeIdentified).toBe(true);
    expect(CLASSIFICATION_RULES.historicalClaimsMustBeTraceable).toBe(true);
  });

  it('has reader disclosure for each classification', () => {
    for (const def of CLASSIFICATION_DEFINITIONS) {
      expect(def.readerDisclosure).toBeTruthy();
      expect(def.readerDisclosure.length).toBeGreaterThan(0);
    }
  });

  it('has key characteristics for each classification', () => {
    for (const def of CLASSIFICATION_DEFINITIONS) {
      expect(def.keyCharacteristics.length).toBeGreaterThan(0);
    }
  });
});

describe('V3C.44A evidence rules', () => {
  it('defines historical claim rules', () => {
    expect(HISTORICAL_CLAIM_RULES.mustBeTraceableToResearch).toBe(true);
    expect(HISTORICAL_CLAIM_RULES.cannotPromoteWithoutEvidence).toBe(true);
    expect(HISTORICAL_CLAIM_RULES.uncertaintyMustBeVisible).toBe(true);
  });

  it('defines scripture rules', () => {
    expect(SCRIPTURE_RULES.mustUseKJVWording).toBe(true);
    expect(SCRIPTURE_RULES.mustCiteBookChapterVerse).toBe(true);
    expect(SCRIPTURE_RULES.cannotExtendBeyondRecordedText).toBe(true);
  });

  it('defines uncertainty rules', () => {
    expect(UNCERTAINTY_RULES.cannotConvertToCertainty).toBe(true);
    expect(UNCERTAINTY_RULES.unresolvedQuestionsMustBeDisclosed).toBe(true);
    expect(UNCERTAINTY_RULES.attestedMustBeDistinguishedFromInferred).toBe(
      true,
    );
  });

  it('defines reconstruction rules', () => {
    expect(RECONSTRUCTION_RULES.mustStateKnownVsUnknown).toBe(true);
    expect(RECONSTRUCTION_RULES.modernAdaptationsMustBeIdentified).toBe(true);
    expect(
      RECONSTRUCTION_RULES.cannotClaimExactAncientRecipesWithoutEvidence,
    ).toBe(true);
  });

  it('defines evidence prohibitions', () => {
    expect(EVIDENCE_PROHIBITIONS.length).toBeGreaterThan(0);
    expect(EVIDENCE_PROHIBITIONS).toContain('Fabricated citations');
    expect(EVIDENCE_PROHIBITIONS).toContain('Invented authorities');
    expect(EVIDENCE_PROHIBITIONS).toContain('Certainty inflation');
  });

  it('has combined evidence rules', () => {
    expect(EVIDENCE_RULES.historical).toBeDefined();
    expect(EVIDENCE_RULES.scripture).toBeDefined();
    expect(EVIDENCE_RULES.uncertainty).toBeDefined();
    expect(EVIDENCE_RULES.reconstruction).toBeDefined();
    expect(EVIDENCE_RULES.citation).toBeDefined();
    expect(EVIDENCE_RULES.modernAdaptation).toBeDefined();
  });
});

describe('V3C.44A recipe template', () => {
  it('defines recipe presentation sections', () => {
    expect(RECIPE_SECTIONS.length).toBeGreaterThan(0);
  });

  it('has required sections', () => {
    const required = RECIPE_SECTIONS.filter((s) => s.required);
    expect(required.length).toBeGreaterThan(0);
    expect(required.map((s) => s.id)).toContain('introduction');
    expect(required.map((s) => s.id)).toContain('ingredients');
    expect(required.map((s) => s.id)).toContain('method');
  });

  it('has correct section ordering', () => {
    const orders = RECIPE_SECTIONS.map((s) => s.order);
    const sorted = [...orders].sort((a, b) => a - b);
    expect(orders).toEqual(sorted);
  });

  it('defines presentation metadata', () => {
    expect(RECIPE_PRESENTATION_METADATA.requiredFields.length).toBeGreaterThan(
      0,
    );
    expect(
      RECIPE_PRESENTATION_METADATA.recommendedFields.length,
    ).toBeGreaterThan(0);
  });

  it('can get required fields for classification', () => {
    const inspired = getRequiredFieldsForClassification(
      'scripture-inspired-preparation',
    );
    expect(inspired).toContain('title');
    expect(inspired).toContain('ingredients');

    const reconstructed =
      getRequiredFieldsForClassification('modern-adaptation');
    expect(reconstructed).toContain('historicalContext');
    expect(reconstructed).toContain('evidenceNotes');
  });

  it('reconstructed recipes require more fields than inspired', () => {
    const inspired = getRequiredFieldsForClassification(
      'scripture-inspired-preparation',
    );
    const reconstructed =
      getRequiredFieldsForClassification('modern-adaptation');
    expect(reconstructed.length).toBeGreaterThan(inspired.length);
  });
});

describe('V3C.44A structural integrity', () => {
  it('chapter target recipes sum to total target', () => {
    const chapterTotal = COOKBOOK_CHAPTERS.reduce(
      (sum, ch) => sum + ch.targetRecipes,
      0,
    );
    expect(chapterTotal).toBe(TARGET_RECIPE_COUNT);
  });

  it('every chapter has a description', () => {
    for (const chapter of COOKBOOK_CHAPTERS) {
      expect(chapter.description).toBeTruthy();
      expect(chapter.description.length).toBeGreaterThan(0);
    }
  });

  it('every chapter has food categories', () => {
    for (const chapter of COOKBOOK_CHAPTERS) {
      expect(chapter.foodCategories.length).toBeGreaterThan(0);
    }
  });

  it('no chapter has duplicate food categories', () => {
    for (const chapter of COOKBOOK_CHAPTERS) {
      expect(new Set(chapter.foodCategories).size).toBe(
        chapter.foodCategories.length,
      );
    }
  });

  it('front matter has methodology referencing existing content', () => {
    const methodology = FRONT_MATTER.find((c) => c.id === 'methodology');
    expect(methodology?.existingContentSource).toBeTruthy();
  });

  it('back matter has auto-generated components with data sources', () => {
    const autoGenerated = BACK_MATTER.filter((c) => c.autoGenerated);
    for (const component of autoGenerated) {
      expect(component.dataSource).toBeTruthy();
    }
  });
});
